Import numpy as np and print the version number.

In [146]:
import numpy as np
print(np.__version__)

1.16.2


Create a 1D array of numbers from 0 to 9

In [2]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

Create a 3×3 numpy array of all True’s

In [169]:
np.full((3,3),True)

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

Extract all odd numbers from arr

In [147]:
arr = np.arange(1,10)
arr[arr%2!=0]

array([1, 3, 5, 7, 9])

Replace all odd numbers in arr with -1

In [10]:
arr[arr%2 != 0] = -1
arr

array([-1,  2, -1,  4, -1,  6, -1,  8, -1])

Convert a 1D array to a 2D array with 2 rows

In [22]:
a = np.arange(8)
b = a.reshape(2,4)
b

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

Stack arrays a and b vertically
> `a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)`

In [165]:
a = np.arange(10).reshape(2,-1)
b = np.repeat(1, 10).reshape(2,-1)

np.vstack((a,b))

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

Stack the arrays a and b horizontally.

In [28]:
np.hstack((a,b))

array([[0, 1, 2, 3, 4, 1, 1, 1, 1, 1],
       [5, 6, 7, 8, 9, 1, 1, 1, 1, 1]])

Get the positions where elements of a and b match<br>

Input:<br>

> `a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])`

In [44]:
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
# a[a == b]
a == b

array([False,  True, False,  True, False,  True, False,  True, False,
       False])

Get all items between 5 and 10 from a.<br>

Input:<br>

>`a = np.array([2, 6, 1, 9, 10, 3, 27])`

In [48]:
a = np.array([2, 6, 1, 9, 10, 3, 27])
a[(a>5) & (a<10)]

array([6, 9])

<pre>Convert the function maxx that works on two scalars, to work on two arrays.

Input:

def maxx(x, y):
    """Get the maximum of two items"""
    if x >= y:
        return x
    else:
        return y

maxx(1, 5)
#> 5
Desired Output:

a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
pair_max(a, b)
#> array([ 6.,  7.,  9.,  8.,  9.,  7.,  5.])</pre>

In [50]:
a = np.array([5, 7, 9, 8, 6, 4, 5])
b = np.array([6, 3, 4, 8, 9, 7, 1])
def greater(a,b):
    if a > b:
        return a
    else:
        return b
vgreater=np.vectorize(greater)
vgreater(a,b)

array([6, 7, 9, 8, 9, 7, 5])

<pre>swap columns 1 and 2 in the array arr.

arr = np.arange(9).reshape(3,3)
arr</pre

In [119]:
arr = np.arange(9).reshape(3,3)
print(arr)
print(arr[:,1:2])
temp=arr[:,1:2] 
print(arr)
print(temp)
arr[:,1:2] = arr[:,2:3]
# print(temp)
arr[:,2:] = temp
# arr = arr[:,1:2]
# arr[:,2:]
arr

[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1]
 [4]
 [7]]
[[0 1 2]
 [3 4 5]
 [6 7 8]]
[[1]
 [4]
 [7]]


array([[0, 2, 2],
       [3, 5, 5],
       [6, 8, 8]])

In [145]:
arr = np.arange(9).reshape(3,3)
# print(arr)
print(arr[:,[0,2,1]])

[[0 2 1]
 [3 5 4]
 [6 8 7]]


<pre>How to reverse the rows of a 2D array?

arr = np.arange(9).reshape(3,3)
arr</pre

In [92]:
arr = np.arange(9).reshape(3,3)
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

<pre>Reverse the columns of a 2D array arr.
arr = np.arange(9).reshape(3,3)
arr</pre>

In [95]:
arr = np.arange(9).reshape(3,3)
arr.T

array([[0, 3, 6],
       [1, 4, 7],
       [2, 5, 8]])

Write a NumPy program to generate five random numbers from the normal distribution

In [170]:
a = np.random.normal(size = 5)
a

array([-2.67134597, -0.77582486,  0.68424192, -0.64448616,  0.93978863])

Write a NumPy program to generate six random integers between 10 and 30

In [167]:
a = np.random.randint(10,30,6)
a

array([18, 25, 11, 22, 10, 24])

Write a NumPy program to create a 3x3x3 array with random values

In [155]:
a = np.random.rand(27).reshape(3,3,3)
a

array([[[0.76017619, 0.23230392, 0.54382722],
        [0.45865765, 0.4235    , 0.31149601],
        [0.11940331, 0.76827524, 0.81664844]],

       [[0.03113882, 0.46306808, 0.8344096 ],
        [0.11426564, 0.08719159, 0.82001879],
        [0.01077232, 0.77364026, 0.21712281]],

       [[0.65188049, 0.52429684, 0.47355822],
        [0.36955196, 0.7764156 , 0.74879835],
        [0.41240827, 0.65965389, 0.69455403]]])

Write a NumPy program to create a 5x5 array with random values and find the minimum and maximum values.

In [157]:
a = np.random.rand(25).reshape(5,5)
print(np.min(a))
print(np.max(a))

0.08956137898100824
0.907355640700098


Write a NumPy program to create a random 10x4 array and extract the first five rows of the array and store them into a variable

In [161]:
a = np.random.rand(40).reshape(10,4)
b = a[0:5]
b

array([[0.44329326, 0.687747  , 0.3984279 , 0.53540648],
       [0.3840523 , 0.74764409, 0.08176936, 0.0787334 ],
       [0.57275283, 0.65945425, 0.98946023, 0.17509907],
       [0.07197941, 0.93349164, 0.03285336, 0.72460829],
       [0.98267948, 0.29697415, 0.2112933 , 0.9878933 ]])

 Write a NumPy program to shuffle numbers between 0 and 10 (inclusive).

In [186]:
a = np.arange(0,11)
b = np.random.shuffle(a)

Read an JPEG image into a numpy array, return the size and shap of that image


In [101]:
# %matplotlib inline#For displaying the result in same cell it self 
import matplotlib.pyplot as plt
img = plt.imread('pic.png')
print(img.shape)
print(img.size)

(511, 512, 4)
1046528
